import type { Metadata } from 'next'

import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
import { ErrorModal } from '../components/error-modal'
import { AuthProvider } from '../hooks/auth-context'
import { ErrorModalProvider } from '../hooks/ui/error-modal-context'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ErrorModalProvider>
            {children}
            <ErrorModal />
          </ErrorModalProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
